version: "3"

services:
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop3.2.1-java8
    container_name: namenode
    restart: always
    ports:
      - 9870:9870
    volumes:
      - hadoop_namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
      - HDFS_CONF_dfs_blocksize=67108864  # Block size 64 MB
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 2G  # Memory limit 2 GB

  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop3.2.1-java8
    container_name: datanode
    restart: always
    volumes:
      - hadoop_datanode:/hadoop/dfs/data
    environment:
      SERVICE_PRECONDITION: "namenode:9870"
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 4G  # Memory limit 4 GB

  spark-master:
    image: bde2020/spark-master:3.0.0-hadoop3.2
    container_name: spark-master
    depends_on:
      - namenode
      - datanode
    ports:
      - "8080:8080"
      - "7077:7077"
    environment:
      - INIT_DAEMON_STEP=setup_spark
    env_file:
      - ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 2G

  spark-worker-1:
    build:
      context: .
      dockerfile: dockerfile
    container_name: spark-worker-1
    depends_on:
      - spark-master
    ports:
      - "8081:8081"
    volumes:
      - ../src/regularSpark.py:/opt/spark-apps/regularSpark.py
      - ../src/functions.py:/opt/spark-apps/functions.py
      - ../src/optimSpark.py:/opt/spark-apps/optimSpark.py
      - ../src/parsing_args.py:/opt/spark-apps/parsing_args.py
    environment:
      - "SPARK_MASTER=spark://spark-master:7077"
    env_file:
      ./hadoop.env
    deploy:
      resources:
        limits:
          memory: 4G # Memory limit 4 GB
  
volumes:
  hadoop_namenode:
  hadoop_datanode:
